<?php include ('header.php'); ?>
        <h1>Update Customer</h1>
    </div>
    <div class="col-md-6 center-block">
        <form class="pure-form" method="post" action="/customer/update/<?=$customer->getId()?>">
            <div class="form-group">
                <label for="first_name">First Name</label>
                <input name="first_name" id="first_name" type="text" class="form-control" required value="<?=$customer->getFirstName()?>" />
            </div>

            <div class="form-group">
                <label for="last_name">Last Name</label>
                <input name="last_name" id="last_name" type="text" class="form-control" required value="<?=$customer->getLastName()?>" />
            </div>

            <div class="form-group">
                <label for="company">Company</label>
                <input name="company" id="company" type="text" class="form-control" value="<?=$customer->getCompany()?>" />
            </div>

            <div class="form-group">
                <label for="job_title">Job Title</label>
                <input name="job_title" id="job_title" type="text" class="form-control" value="<?=$customer->getJobTitle()?>" />
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input name="email" id="email" type="email" class="form-control" required value="<?=$customer->getEmail()?>" />
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input name="phone" id="phone" type="text" class="form-control" value="<?=$customer->getPhone()?>" />
            </div>

            <div class="form-group">
                <label for="website">Website</label>
                <input name="website" id="website" type="text" class="form-control" value="<?=$customer->getWebsite()?>" />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">Update</button>
            </div>
        </form>

    </div>

<?php include ('footer.php'); ?>