<?php include ('header.php'); ?>
        <h1>New Customer</h1>
    </div>
    <div class="col-md-6 center-block">
        <form class="pure-form" method="post" action="/customer/new">
            <div class="form-group">
                <label for="first_name">First Name</label>
                <input name="first_name" id="first_name" type="text" class="form-control" required/>
            </div>

            <div class="form-group">
                <label for="last_name">Last Name</label>
                <input name="last_name" id="last_name" type="text" class="form-control" required/>
            </div>
            
            <div class="form-group">
                <label for="company">Company</label>
                <input name="company" id="company" type="text" class="form-control" />
            </div>
            
            <div class="form-group">
                <label for="job_title">Job Title</label>
                <input name="job_title" id="job_title" type="text" class="form-control" />
            </div>
            
            <div class="form-group">
                <label for="email">Email</label>
                <input name="email" id="email" type="email" class="form-control" required/>
            </div>
            
            <div class="form-group">
                <label for="phone">Phone</label>
                <input name="phone" id="phone" type="text" class="form-control" />
            </div>
            
            <div class="form-group">
                <label for="website">Website</label>
                <input name="website" id="website" type="text" class="form-control" placeholder="http://" />
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">Create</button>
            </div>
        </form>
    </div>

<?php include ('footer.php'); ?>
